name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:

  build:
    environment: prod

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.3.0
      with:
        context: ./backend
        file: ./backend/Dockerfile
        no-cache: true
        push: true
        tags: erik-uy/obico-server:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
